## 다중 선형 회귀 구현하기


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

In [4]:
# Data
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152],
                             [185],
                             [196],
                             [142]])

In [7]:
# model을 설정. Multi variate Linear Regression 이므로 input_dim=3, output_dim=1
model = nn.Linear(3, 1)
print(list(model.parameters())) # 입력 차원이 3이므로 3개의 가중치 w와 편향 b가 저장되어있음

[Parameter containing:
tensor([[ 0.0803, -0.0707,  0.1601]], requires_grad=True), Parameter containing:
tensor([0.0285], requires_grad=True)]


In [8]:
# optimizer 설정
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [10]:
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    prediction = model(x_train) # forward(순전파) 연산
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad() # optimizer 초기화
    cost.backward() # cost 함수를 미분해서 gradietn 계산
    optimizer.step() # W와 b를 업데이트
    
    if epoch % 100 == 0:
        print(f"Epoch {epoch:4d}/{nb_epochs} Cost : {cost.item():.6f}")

Epoch    0/2000 Cost : 0.551485
Epoch  100/2000 Cost : 0.541659
Epoch  200/2000 Cost : 0.532326
Epoch  300/2000 Cost : 0.523442
Epoch  400/2000 Cost : 0.514989
Epoch  500/2000 Cost : 0.506958
Epoch  600/2000 Cost : 0.499293
Epoch  700/2000 Cost : 0.491985
Epoch  800/2000 Cost : 0.485016
Epoch  900/2000 Cost : 0.478358
Epoch 1000/2000 Cost : 0.472002
Epoch 1100/2000 Cost : 0.465926
Epoch 1200/2000 Cost : 0.460107
Epoch 1300/2000 Cost : 0.454536
Epoch 1400/2000 Cost : 0.449191
Epoch 1500/2000 Cost : 0.444063
Epoch 1600/2000 Cost : 0.439155
Epoch 1700/2000 Cost : 0.434425
Epoch 1800/2000 Cost : 0.429888
Epoch 1900/2000 Cost : 0.425503
Epoch 2000/2000 Cost : 0.421300


In [12]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7995, 0.4619, 0.7495]], requires_grad=True), Parameter containing:
tensor([0.0422], requires_grad=True)]


In [13]:
# 임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])

# 입력한 값 [73, 80 ,75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print(f"학습 후 입력이 73, 80, 75일 때의 예측값 : {pred_y}")

학습 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.5749]], grad_fn=<AddmmBackward0>)
