In [1]:
import numpy as np
import torch

In [2]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [3]:
W = torch.zeros(1, requires_grad=True) # 'requires_grad=True' : 이 변수를 학습시킬 것을 나타낸다
b = torch.zeros(1, requires_grad=True)

In [4]:
optimizer = torch.optim.SGD([W, b], lr=0.01)

nb_epochs = 1000
for epoch in range(1, nb_epochs + 1):
    hypothesis = W * x_train + b
    cost = torch.mean((hypothesis - y_train) ** 2) # Mean Squared Error (MSE)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

In [5]:
print(W)
print(b)

tensor([1.9708], requires_grad=True)
tensor([0.0664], requires_grad=True)


# nn.Module로 구현하는 선형 회귀

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
torch.manual_seed(1)

In [8]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [9]:
model = nn.Linear(1, 1) # 모델을 선언 및 초기화. 단순 선형 회기이므로 input_dim=1, output_dim=1

In [10]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) # optimizer 설정. 경사 하강법 SGD를 사용

In [11]:
# 전체 train data에 대해서 경사 하강법을 2,000회 반복

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== PyTorch에서 제공하는 MSE 함수
    
    # cost로 H(x) 개선하는 부분
    
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward(역전파) 연산
    # W와 b 업데이트
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f"Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f}")

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


## 학습 결과 확인

In [12]:
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([4.0])

# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward(순전파) 연산

# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print(f"훈련 후 입력이 4일 때의 예측값 : {pred_y}") 


훈련 후 입력이 4일 때의 예측값 : tensor([7.9989], grad_fn=<AddBackward0>)


In [13]:
# 학습 후 W와 b 값을 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


W의 값이 2에 가깝고, b의 값이 0에 가까운 것을 확인할 수 있다.

# class로 PyTorch 모델 구현하기

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### 단순 선형 회기

In [4]:
class LinearRegressionModel(nn.Module): # 여기서 nn.Module 을 적는 이유 : 직접 모델을 구성할 때는 nn.Module의 subclass에 새로운 Module을 정의한다.
    def __init__(self):
        super().__init__() # super() 함수를 부르면 nn.Module 클래스의 속성을 가지고 초기화됨
        self.linear = nn.Linear(1, 1) # 단순선형회귀이므로 input_dim=1, output_dim=1
        
    def forward(self, x):
        return self.linear(x)

In [9]:
model = LinearRegressionModel()

*optimizer을 설정하고 parameters를 training하는 부분은 위의 코드와 같다*

### 다중 선형 회귀

In [7]:
class MultivariateLinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회기이고, 여기서는 input_dim=3, output_dim=1
        
    def forward(self, x):
        return self.linear(x)

In [8]:
model = MultivariateLinearRegression()

*optimizer을 설정하고 parameters를 training하는 부분은 위의 코드와 같다*