# XOR 문제 - 단층 퍼셉트론 구하기

In [8]:
import torch
import torch.nn as nn

In [6]:
device = torch.device("mps")
torch.cuda.manual_seed(777)

In [7]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device) # XOR 출력값

In [9]:
linear = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()
model = nn.Sequential(linear, sigmoid).to(device)

In [10]:
# 비용 함수와 옵티마이저 정의
criterion = nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [11]:
for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)
    
    # 비용 함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()
    
    if step % 100 == 0:
        print(step, ":", cost.item())

0 : 0.7231569886207581
100 : 0.6931471824645996
200 : 0.6931471228599548
300 : 0.6931471824645996
400 : 0.6931471824645996
500 : 0.6931471824645996
600 : 0.6931471824645996
700 : 0.6931471824645996
800 : 0.6931471824645996
900 : 0.6931471824645996
1000 : 0.6931471824645996
1100 : 0.6931471824645996
1200 : 0.6931471824645996
1300 : 0.6931471824645996
1400 : 0.6931471824645996
1500 : 0.6931471824645996
1600 : 0.6931471824645996
1700 : 0.6931471824645996
1800 : 0.6931471824645996
1900 : 0.6931471824645996
2000 : 0.6931471824645996
2100 : 0.6931471824645996
2200 : 0.6931471824645996
2300 : 0.6931471824645996
2400 : 0.6931471824645996
2500 : 0.6931471824645996
2600 : 0.6931471824645996
2700 : 0.6931471824645996
2800 : 0.6931471824645996
2900 : 0.6931471824645996
3000 : 0.6931471824645996
3100 : 0.6931471824645996
3200 : 0.6931471824645996
3300 : 0.6931471824645996
3400 : 0.6931471824645996
3500 : 0.6931471824645996
3600 : 0.6931471824645996
3700 : 0.6931471824645996
3800 : 0.693147182464599

In [18]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print("모델의 출력값(Hypothesis): \n", hypothesis.detach().cpu().numpy())
    print("모델의 예측값(Predicted: \n", predicted.detach().cpu().numpy())
    print("실제값(Y): \n", Y.cpu().numpy())
    print("정확도(Accuracy): \n", accuracy.item())

모델의 출력값(Hypothesis): 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
모델의 예측값(Predicted: 
 [[0.]
 [0.]
 [0.]
 [0.]]
실제값(Y): 
 [[0.]
 [1.]
 [1.]
 [0.]]
정확도(Accuracy): 
 0.5


# XOR 문제 - 다층 퍼셉트론 구하기

In [19]:
import torch
import torch.nn as nn

In [21]:
device = torch.device("mps")

torch.manual_seed(777)

In [27]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device) # XOR 입력값
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device) # XOR 출력값

In [28]:
model = nn.Sequential(
    nn.Linear(2, 10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10, 10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10, 10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10, 1, bias=True),
    nn.Sigmoid()
).to(device)

In [29]:
criterion = nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [30]:
for epoch in range(10001):
    optimizer.zero_grad()
    # forward 연산
    hypothesis = model(X)
    
    # 비용 함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(epoch, cost.item())

0 0.6948983669281006
100 0.6931556463241577
200 0.6931535005569458
300 0.6931513547897339
400 0.6931493282318115
500 0.6931472420692444
600 0.6931453347206116
700 0.6931434273719788
800 0.6931415796279907
900 0.6931397914886475
1000 0.6931379437446594
1100 0.6931360960006714
1200 0.6931342482566833
1300 0.6931322813034058
1400 0.6931304335594177
1500 0.6931284070014954
1600 0.693126380443573
1700 0.6931242942810059
1800 0.6931220293045044
1900 0.6931196451187134
2000 0.693117082118988
2100 0.6931143999099731
2200 0.6931115388870239
2300 0.6931084394454956
2400 0.6931051015853882
2500 0.6931014657020569
2600 0.6930973529815674
2700 0.693092942237854
2800 0.6930879950523376
2900 0.6930824518203735
3000 0.6930763125419617
3100 0.6930692195892334
3200 0.6930612325668335
3300 0.6930519342422485
3400 0.6930410861968994
3500 0.6930283904075623
3600 0.6930133104324341
3700 0.6929950714111328
3800 0.6929728388786316
3900 0.6929452419281006
4000 0.6929102540016174
4100 0.6928650140762329
4200 0.

In [33]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('모델의 출력값(Hypothesis): ', hypothesis.detach().cpu().numpy())
    print('모델의 예측값(Predicted): ', predicted.detach().cpu().numpy())
    print('실제값(Y): ', Y.cpu().numpy())
    print('정확도(Accuracy): ', accuracy.item())

모델의 출력값(Hypothesis):  [[1.1171795e-04]
 [9.9982876e-01]
 [9.9984223e-01]
 [1.8531324e-04]]
모델의 예측값(Predicted):  [[0.]
 [1.]
 [1.]
 [0.]]
실제값(Y):  [[0.]
 [1.]
 [1.]
 [0.]]
정확도(Accuracy):  1.0


개쩐다